export const allVracs = [
  {
    id: 1,
    nom: "Anneaux à l'Ananas",
    img: "images/Vrac/Bonbons/Anneaux_A_L'Ananas.png",
    tag: ["Ananas"],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 2,
    nom: "Anneaux à la Fraise",
    img: "images/Vrac/Bonbons/Anneaux_A_La_Fraise.png",
    tag: ["Fraise"],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 3,
    nom: "Anneaux à la Peche",
    img: "images/Vrac/Bonbons/Anneaux_A_La_Peche.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 4,
    nom: "Anneaux au Raisin",
    img: "images/Vrac/Bonbons/Anneaux_Au_Raisin.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 5,
    nom: "Bouchée sure à l'Ananas et Orange",
    img: "images/Vrac/Bonbons/Bouchee_Sure_A_L'Ananas_Et_Orange.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 6,
    nom: "Boule Sure à la Cerise",
    img: "images/Vrac/Bonbons/Boule_Sure_A_La_Cerise.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 7,
    nom: "Boule Sure à la Pomme",
    img: "images/Vrac/Bonbons/Boule_Sure_A_La_Pomme.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 8,
    nom: "Bouteille à la Gomme Balloune",
    img: "images/Vrac/Bonbons/Bouteille_A_La_Gomme_Balloune.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 8,
    nom: "Bouteille de Cola",
    img: "images/Vrac/Bonbons/Bouteille_De_Cola.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 9,
    nom: "Coeur de Conversation Sure",
    img: "images/Vrac/Bonbons/Coeur_De_Conversation_Sure.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 10,
    nom: "Délice à la Framboise",
    img: "images/Vrac/Bonbons/Delice_A_La_Framboise.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 11,
    nom: "Dinosaure",
    img: "images/Vrac/Bonbons/Dinosaure.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 12,
    nom: "Flamants Roses à la Cerise",
    img: "images/Vrac/Bonbons/Flamants_Roses_A_La_Cerise.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 13,
    nom: "Fraise Lunaire",
    img: "images/Vrac/Bonbons/Fraise_Lunaire.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 14,
    nom: "Framboise Lunaire",
    img: "images/Vrac/Bonbons/Framboise_Lunaire.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 15,
    nom: "Grenouille",
    img: "images/Vrac/Bonbons/Grenouille.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 16,
    nom: "Lait Frappe à la Fraise",
    img: "images/Vrac/Bonbons/Lait_Frappe_A_La_Fraise.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 17,
    nom: "Lèvres Chaudes",
    img: "images/Vrac/Bonbons/Levres_Chaudes.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 18,
    nom: "Licorne",
    img: "images/Vrac/Bonbons/Licorne.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 19,
    nom: "Mangue Épicée",
    img: "images/Vrac/Bonbons/Mangue_Epicee.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 20,
    nom: "Mini Framboise",
    img: "images/Vrac/Bonbons/Mini_Framboise.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 21,
    nom: "Oeuf",
    img: "images/Vrac/Bonbons/Oeuf.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 22,
    nom: "Ourson à la Mangue",
    img: "images/Vrac/Bonbons/Ourson_A_La_Mangue.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 23,
    nom: "Ourson Pamplemousse",
    img: "images/Vrac/Bonbons/Ourson_Pamplemousse.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 24,
    nom: "Ourson Saveur Variée",
    img: "images/Vrac/Bonbons/Ourson_Saveur_Variee.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 25,
    nom: "Petite Suce",
    img: "images/Vrac/Bonbons/Petite_Suce.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 26,
    nom: "Petits Fruits",
    img: "images/Vrac/Bonbons/Petits_Fruits.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 27,
    nom: "Soda Banane",
    img: "images/Vrac/Bonbons/Soda_Banane.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 28,
    nom: "Sucette Glacée",
    img: "images/Vrac/Bonbons/Sucette_Glacee.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 29,
    nom: "Tarte à la Fraise",
    img: "images/Vrac/Bonbons/Tarte_A_La_Fraise.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 30,
    nom: "Tranche de Kiwi",
    img: "images/Vrac/Bonbons/Tranche_De_Kiwi.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 31,
    nom: "Tranche de Melon d'Eau Sure",
    img: "images/Vrac/Bonbons/Tranche_De_Melon_D'Eau_Sure.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
]

export const allProducts = [
  {
    id: 1,
    nom: "Mike & Ike Original",
    prix: 3.79,
    img: "images/Produits/Exotique/Mike_Ike_Original.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 2,
    nom: "Mike & Ike Tropical",
    prix: 3.79,
    img: "images/Produits/Exotique/Mike_Ike_Tropical.png",
    tag: ["Exotique", "Tropical"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 3,
    nom: "Mike & Ike Baie",
    prix: 3.79,
    img: "images/Produits/Exotique/Mike_Ike_Baie.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 4,
    nom: "Ghost Pepper Framboise Bleue",
    prix: 5.89,
    img: "images/Produits/Exotique/Gost_Pepper_Framboise_Bleue.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 5,
    nom: "Ghost Pepper Cerise",
    prix: 5.89,
    img: "images/Produits/Exotique/Ghost_Pepper_Cerise.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 6,
    nom: "Paille Céréale Cocoa Krispie",
    prix: 5.99,
    img: "images/Produits/Exotique/Pailles_Cereale_Cocoa_Krispie.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 7,
    nom: "Paille Froot Loops",
    prix: 5.99,
    img: "images/Produits/Exotique/Pailles_Froot_Loops.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 8,
    nom: "Gummi Eyes Herbert's",
    prix: 7.99,
    img: "images/Produits/Exotique/Gummi_Eyes_Herberts.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 9,
    nom: "Starbust Fraise",
    prix: 3.25,
    img: "images/Produits/Exotique/Starbust_Fraise.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 10,
    nom: "Pickle, Cornichon Big Papa",
    prix: 3.99,
    img: "images/Produits/Exotique/Cornichon_Big_Papa.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },

  {
    id: 11,
    nom: "Pickle, Cornichon Hot Mama",
    prix: 3.99,
    img: "images/Produits/Exotique/Cornichon_Hot_Mama.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 12,
    nom: "Pickle, Cornichon Sour Sis",
    prix: 3.99,
    img: "images/Produits/Exotique/Cornichon_Sour_Sis.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 13,
    nom: "Warheads Galactic Mix",
    prix: 3.99,
    img: "images/Produits/Exotique/Warheads_Galactic_Mix.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 14,
    nom: "Warheads Cubes Framboisés Bleues",
    prix: 3.99,
    img: "images/Produits/Exotique/Warheads_Cubes_Framboises_Bleues.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 15,
    nom: "Warheads Mega Sour Booms",
    prix: 4.78,
    img: "images/Produits/Exotique/Warheads_Mega_Sour_Booms.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 16,
    nom: "Warheads Wedgies",
    prix: 3.99,
    img: "images/Produits/Exotique/Warheads_Wedgies.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 17,
    nom: "Chipsnuts Cornichon à l'Aneth",
    prix: 2.99,
    img: "images/Produits/Exotique/Chipsnuts_Cornichon_A_L'Aneth.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 18,
    nom: "Chipnuts Sel et Vinaigre",
    prix: 2.99,
    img: "images/Produits/Exotique/Chipnuts_Sel_Et_Vinaigre.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 19,
    nom: "Chipnuts BBQ de Sud",
    prix: 2.99,
    img: "images/Produits/Exotique/Chipnuts_BBQ_De_Sud.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 20,
    nom: "Nerds Gummy Clusters Berry Berry",
    prix: 6.59,
    img: "images/Produits/Exotique/Nerds_Gummy_Clusters_Berry_Berry.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 21,
    nom: "Sweet Tarts Chewy Fusion Punch aux Fruits",
    prix: 5.89,
    img: "images/Produits/Exotique/Sweet_Tarts_Chewy_Fusion_Punch_Aux_Fruits.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 22,
    nom: "Sweet Tarts Ropes Fraise",
    prix: 5.99,
    img: "images/Produits/Exotique/Sweet_Tarts_Ropes_Fraise.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
    {
    id: 23,
    nom: "Fruity's Snacks",
    prix: 6.99,
    img: "images/Produits/Exotique/Fruity's_Snacks.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 24,
    nom: "Coupes de Pudding au Chocolat au Lait",
    prix: 5.50,
    img: "images/Produits/Exotique/Coupes_De_Pudding_Au_Chocolat_Au_Lait.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 25,
    nom: "Chili Peppers",
    prix: 3.99,
    img: "images/Produits/Exotique/Chili_Peppers.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 26,
    nom: "Toxic Waste",
    prix: 3.99,
    img: "images/Produits/Exotique/Toxic_Waste.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 27,
    nom: "Hot Tamales",
    prix: 3.99,
    img: "images/Produits/Exotique/Hot_Tamales.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 28,
    nom: "Bon Bons à la Fraise",
    prix: 4.99,
    img: "images/Produits/Antan/Bon_Bons_A_La_Fraise.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 29,
    nom: "Bon Bons Framboise Bleue",
    prix: 4.99,
    img: "images/Produits/Antan/Bon_Bons_Framboise_Bleue.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 30,
    nom: "Casse Gueule",
    prix: 3.95,
    img: "images/Produits/Antan/Casse_Gueule.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 31,
    nom: "Charleston Chew, Nougat à la Fraise",
    prix: 3.59,
    img: "images/Produits/Antan/Charleston_Chew_Nougat_Fraise.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 32,
    nom: "Gold Mine Gomme",
    prix: 3.99,
    img: "images/Produits/Antan/Gold_Mine_Gomme.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 33,
    nom: "Lune de Miel",
    prix: 6.99,
    img: "images/Produits/Antan/Lune_De_Miel.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 34,
    nom: "Oublie Rondes au Goût d'Hosties",
    prix: 1.95,
    img: "images/Produits/Antan/Oublies_Rondes_Au_Gout_Dhosties.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 35,
    nom: "Pastilles aux Fruits",
    prix: 5.69,
    img: "images/Produits/Antan/Pastilles_Aux_Fruits.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 36,
    nom: "Soucoupes Volantes à la Poudre Surette",
    prix: 5.89,
    img: "images/Produits/Antan/Soucoupes_Volantes_A_La_Poudre_Surette.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 37,
    nom: "Sugar Daddy Caramel",
    prix: 3.49,
    img: "images/Produits/Antan/Sugar_Daddy_Caramel.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 38,
    nom: "Taffy aux Fruits",
    prix: 2.49,
    img: "images/Produits/Antan/Taffy_Aux_Fruits.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 39,
    nom: "Taffy Napolitaine",
    prix: 2.49,
    img: "images/Produits/Antan/Taffy_Napolitaine.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 40,
    nom: "Anneaux à la Pêche Sucré 55g",
    prix: 11.49,
    img: "images/Produits/Lyophilises/Anneaux_A_La_Peche_Sucre.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 41,
    nom: "Anneaux à la Pêche Surette 55g",
    prix: 11.49,
    img: "images/Produits/Lyophilises/Anneaux_A_La_Peche_Surette.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 42,
    nom: "Bébé Ours 50g",
    prix: 11.49,
    img: "images/Produits/Lyophilises/Bebe_Ours.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 43,
    nom: "Puffy Gummy Virus (Nerds) 25g",
    prix: 8.49,
    img: "images/Produits/Lyophilises/Puffy_Gummy_Virus.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 44,
    nom: "Rainbow Crunch Suret (Skittles) 120g",
    prix: 11.49,
    img: "images/Produits/Lyophilises/Rainbow_Crunch_Suret.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 45,
    nom: "Rainbow Crunch (Skittles) Régulier 120g",
    prix: 11.49,
    img: "images/Produits/Lyophilises/Rainbow_Crunch.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 46,
    nom: "Taffy à la Fraise 28g",
    prix: 8.49,
    img: "images/Produits/Lyophilises/Taffy_A_La_Fraise.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 47,
    nom: "Verre de Terre 52g",
    prix: 11.49,
    img: "images/Produits/Lyophilises/Verre_De_Terre.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  }
]

export const CarrouselEvenements = [
  {
    id: 1,
    img: "images/Evenements/Chapo.png",
    info: "Du 13 au 15 septembre 2024, à 1089 Montée Masson, Mascouche (Qc) J7K 2M1! Venez nous visiter durant le festival pour découvrir une panoplie de bonbons de toutes sorte!"
  },
  {
    id: 2,
    img: "images/Evenements/Halloween.jpg",
    info: "Restez à l'affut pour nos nouveautés saisonnales. Contacter nous par l'onglet Bar à Bonbons pour passer votre commande pour l'Halloween!🎃"
  },
  {
    id: 3,
    img: "images/Evenements/Noel.png",
    info: "Restez à l'affut pour nos nouveautés saisonnales. De délicieuses pâtisseries exclusives pour le temps des fêtes!🎅🏻🌲"
  },
  {
    id: 4,
    img: "images/Evenements/FeteQuebec.jpg",
    info: "Nous sommes ouvert durant la fête du Québec! Venez nous voir pour des bundles de bonbons thématiques Québec! 🔵⚜️⚪"
  }
]