export const allVracs = [
  {
    id: 1,
    nom: "Anneaux à l'Ananas",
    img: "images/Vrac/Bonbons/0.png",
    tag: ["Ananas"],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 2,
    nom: "Anneaux à la Fraise",
    img: "images/Vrac/Bonbons/1.png",
    tag: ["Fraise"],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 3,
    nom: "Anneaux à la Peche",
    img: "images/Vrac/Bonbons/2.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 4,
    nom: "Anneaux au Raisin",
    img: "images/Vrac/Bonbons/3.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 5,
    nom: "Bouchée sure à l'Ananas et Orange",
    img: "images/Vrac/Bonbons/4.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 6,
    nom: "Boule Sure à la Cerise",
    img: "images/Vrac/Bonbons/5.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 7,
    nom: "Boule Sure à la Pomme",
    img: "images/Vrac/Bonbons/6.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 8,
    nom: "Bouteille à la Gomme Balloune",
    img: "images/Vrac/Bonbons/7.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 8,
    nom: "Bouteille de Cola",
    img: "images/Vrac/Bonbons/8.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 9,
    nom: "Coeur de Conversation Sure",
    img: "images/Vrac/Bonbons/9.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 10,
    nom: "Délice à la Framboise",
    img: "images/Vrac/Bonbons/10.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 11,
    nom: "Dinosaure",
    img: "images/Vrac/Bonbons/11.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 12,
    nom: "Flamants Roses à la Cerise",
    img: "images/Vrac/Bonbons/12.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 13,
    nom: "Fraise Lunaire",
    img: "images/Vrac/Bonbons/13.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 14,
    nom: "Framboise Lunaire",
    img: "images/Vrac/Bonbons/14.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 15,
    nom: "Grenouille",
    img: "images/Vrac/Bonbons/15.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 16,
    nom: "Lait Frappe à la Fraise",
    img: "images/Vrac/Bonbons/16.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 17,
    nom: "Lèvres Chaudes",
    img: "images/Vrac/Bonbons/17.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 18,
    nom: "Licorne",
    img: "images/Vrac/Bonbons/18.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 19,
    nom: "Mangue Épicée",
    img: "images/Vrac/Bonbons/19.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 20,
    nom: "Mini Framboise",
    img: "images/Vrac/Bonbons/20.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 21,
    nom: "Oeuf",
    img: "images/Vrac/Bonbons/21.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 22,
    nom: "Ourson à la Mangue",
    img: "images/Vrac/Bonbons/22.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 23,
    nom: "Ourson Pamplemousse",
    img: "images/Vrac/Bonbons/23.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 24,
    nom: "Ourson Saveur Variée",
    img: "images/Vrac/Bonbons/24.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 25,
    nom: "Petite Suce",
    img: "images/Vrac/Bonbons/25.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 26,
    nom: "Petits Fruits",
    img: "images/Vrac/Bonbons/26.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 27,
    nom: "Soda Banane",
    img: "images/Vrac/Bonbons/27.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 28,
    nom: "Sucette Glacée",
    img: "images/Vrac/Bonbons/28.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 29,
    nom: "Tarte à la Fraise",
    img: "images/Vrac/Bonbons/29.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 30,
    nom: "Tranche de Kiwi",
    img: "images/Vrac/Bonbons/30.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
  {
    id: 31,
    nom: "Tranche de Melon d'Eau Sure",
    img: "images/Vrac/Bonbons/31.png",
    tag: [],
    inventaire: 100,
    nouveau: false,
    actif: true,
  },
]

export const allProducts = [
  {
    id: 1,
    nom: "Mike & Ike Original",
    prix: 3.79,
    img: "images/Produits/0.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 2,
    nom: "Mike & Ike Tropical",
    prix: 3.79,
    img: "images/Produits/1.png",
    tag: ["Exotique", "Tropical"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 3,
    nom: "Mike & Ike Baie",
    prix: 3.79,
    img: "images/Produits/2.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 4,
    nom: "Ghost Pepper Framboise Bleue",
    prix: 5.89,
    img: "images/Produits/3.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 5,
    nom: "Ghost Pepper Cerise",
    prix: 5.89,
    img: "images/Produits/4.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 6,
    nom: "Paille Céréale Cocoa Krispie",
    prix: 5.99,
    img: "images/Produits/5.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 7,
    nom: "Paille Froot Loops",
    prix: 5.99,
    img: "images/Produits/6.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 8,
    nom: "Gummi Eyes Herbert's",
    prix: 7.99,
    img: "images/Produits/7.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 9,
    nom: "Starbust Fraise",
    prix: 3.25,
    img: "images/Produits/8.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 10,
    nom: "Pickle, Cornichon Big Papa",
    prix: 3.99,
    img: "images/Produits/9.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },

  {
    id: 11,
    nom: "Pickle, Cornichon Hot Mama",
    prix: 3.99,
    img: "images/Produits/10.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 12,
    nom: "Pickle, Cornichon Sour Sis",
    prix: 3.99,
    img: "images/Produits/11.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 13,
    nom: "Warheads Galactic Mix",
    prix: 3.99,
    img: "images/Produits/12.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 14,
    nom: "Warheads Cubes Framboisés Bleues",
    prix: 3.99,
    img: "images/Produits/13.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 15,
    nom: "Warheads Mega Sour Booms",
    prix: 4.78,
    img: "images/Produits/14.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 16,
    nom: "Warheads Wedgies",
    prix: 3.99,
    img: "images/Produits/15.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 17,
    nom: "Chipsnuts Cornichon à l'Aneth",
    prix: 2.99,
    img: "images/Produits/16.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 18,
    nom: "Chipnuts Sel et Vinaigre",
    prix: 2.99,
    img: "images/Produits/17.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 19,
    nom: "Chipnuts BBQ de Sud",
    prix: 2.99,
    img: "images/Produits/18.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 20,
    nom: "Nerds Gummy Clusters Berry Berry",
    prix: 6.59,
    img: "images/Produits/19.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 21,
    nom: "Sweet Tarts Chewy Fusion Punch aux Fruits",
    prix: 5.89,
    img: "images/Produits/20.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 22,
    nom: "Sweet Tarts Ropes Fraise",
    prix: 5.99,
    img: "images/Produits/21.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
    {
    id: 23,
    nom: "Fruity's Snacks",
    prix: 6.99,
    img: "images/Produits/22.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 24,
    nom: "Coupes de Pudding au Chocolat au Lait",
    prix: 5.50,
    img: "images/Produits/23.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 25,
    nom: "Chili Peppers",
    prix: 3.99,
    img: "images/Produits/24.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 26,
    nom: "Toxic Waste",
    prix: 3.99,
    img: "images/Produits/25.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 27,
    nom: "Hot Tamales",
    prix: 3.99,
    img: "images/Produits/26.png",
    tag: ["Exotique"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 28,
    nom: "Bon Bons à la Fraise",
    prix: 4.99,
    img: "images/Produits/27.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 29,
    nom: "Bon Bons Framboise Bleue",
    prix: 4.99,
    img: "images/Produits/28.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 30,
    nom: "Casse Gueule",
    prix: 3.95,
    img: "images/Produits/29.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 31,
    nom: "Charleston Chew, Nougat à la Fraise",
    prix: 3.59,
    img: "images/Produits/30.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 32,
    nom: "Gold Mine Gomme",
    prix: 3.99,
    img: "images/Produits/31.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 33,
    nom: "Lune de Miel",
    prix: 6.99,
    img: "images/Produits/32.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 34,
    nom: "Oublie Rondes au Goût d'Hosties",
    prix: 1.95,
    img: "images/Produits/33.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 35,
    nom: "Pastilles aux Fruits",
    prix: 5.69,
    img: "images/Produits/34.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 36,
    nom: "Soucoupes Volantes à la Poudre Surette",
    prix: 5.89,
    img: "images/Produits/35.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 37,
    nom: "Sugar Daddy Caramel",
    prix: 3.49,
    img: "images/Produits/36.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 38,
    nom: "Taffy aux Fruits",
    prix: 2.49,
    img: "images/Produits/37.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 39,
    nom: "Taffy Napolitaine",
    prix: 2.49,
    img: "images/Produits/38.png",
    tag: ["Antan"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 40,
    nom: "Anneaux à la Pêche Sucré 55g",
    prix: 11.49,
    img: "images/Produits/39.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 41,
    nom: "Anneaux à la Pêche Surette 55g",
    prix: 11.49,
    img: "images/Produits/40.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 42,
    nom: "Bébé Ours 50g",
    prix: 11.49,
    img: "images/Produits/41.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 43,
    nom: "Puffy Gummy Virus (Nerds) 25g",
    prix: 8.49,
    img: "images/Produits/42.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 44,
    nom: "Rainbow Crunch Suret (Skittles) 120g",
    prix: 11.49,
    img: "images/Produits/43.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 45,
    nom: "Rainbow Crunch (Skittles) Régulier 120g",
    prix: 11.49,
    img: "images/Produits/44.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 46,
    nom: "Taffy à la Fraise 28g",
    prix: 8.49,
    img: "images/Produits/45.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  },
  {
    id: 47,
    nom: "Verre de Terre 52g",
    prix: 11.49,
    img: "images/Produits/46.png",
    tag: ["Lyophilisés"],
    inventaire: 10,
    nouveau: false,
    actif: true
  }
]

export const CarrouselEvenements = [
  {
    id: 1,
    img: "images/Evenements/Chapo.png",
    info: "Du 13 au 15 septembre 2024, à 1089 Montée Masson, Mascouche (Qc) J7K 2M1! Venez nous visiter durant le festival pour découvrir une panoplie de bonbons de toutes sorte!"
  },
  {
    id: 2,
    img: "images/Evenements/Halloween.jpg",
    info: "Restez à l'affut pour nos nouveautés saisonnales. Contacter nous par l'onglet Bar à Bonbons pour passer votre commande pour l'Halloween!🎃"
  },
  {
    id: 3,
    img: "images/Evenements/Noel.png",
    info: "Restez à l'affut pour nos nouveautés saisonnales. De délicieuses pâtisseries exclusives pour le temps des fêtes!🎅🏻🌲"
  },
  {
    id: 4,
    img: "images/Evenements/FeteQuebec.jpg",
    info: "Nous sommes ouvert durant la fête du Québec! Venez nous voir pour des bundles de bonbons thématiques Québec! 🔵⚜️⚪"
  }
]